import { RequestHandler } from 'express';
import { env } from '../config/env';
import { logger } from '../config/logger';
import { shopify } from '../config/shopify';
import { Shop } from '../models/Shop';
import { installShopFromIdToken } from '../services/shopInstallationService';
import { ensureFreshShopToken } from '../services/shopTokenService';
import { asyncHandler } from '../utils/asyncHandler';
import { AppError } from '../utils/AppError';
export const adminSessionAuth:RequestHandler=asyncHandler(async(req,res,next)=>{const token=req.headers.authorization?.match(/^Bearer (.+)$/)?.[1];if(!token)throw new AppError('Shopify session token required',401,'UNAUTHORIZED');let payload;try{payload=await shopify.session.decodeSessionToken(token);}catch{res.setHeader('X-Shopify-Retry-Invalid-Session-Request','1');throw new AppError('Invalid Shopify session token',401,'INVALID_TOKEN');}const destination=new URL(payload.dest),shopDomain=destination.hostname;let shop=await Shop.findOne({shopDomain,isActive:true}).select('+accessToken +refreshToken');try{if(!shop||!shop.tokenExpiresAt)shop=await installShopFromIdToken(shopDomain,token,env.shopifyAppUrl);else shop=await ensureFreshShopToken(shop);}catch(error:any){logger.error('shop_token_acquisition_failed',{shopDomain,message:error.message});res.setHeader('X-Shopify-Retry-Invalid-Session-Request','1');throw new AppError('Unable to acquire Shopify access',401,'INVALID_TOKEN');}req.shop=shop;next();});
