import bcrypt from 'bcrypt';
import jwt, { SignOptions } from 'jsonwebtoken';
import { Request, Response } from 'express';
import crypto from 'crypto';
import { env } from '../config/env';
import { Customer } from '../models/Customer';
import { Shop } from '../models/Shop';
import { ok } from '../utils/apiResponse';
import { AppError } from '../utils/AppError';
import { findShopifyCustomerByEmail } from '../services/shopifyGraphqlService';
import { LoyaltyRule } from '../models/LoyaltyRule';
import { awardPoints } from '../services/pointsService';
import { Transaction } from '../models/Transaction';
const sign=(customer:any,type:'access'|'refresh')=>jwt.sign({customerId:String(customer._id),shopDomain:customer.shopDomain,tokenType:type},env.jwtSecret,{expiresIn:(type==='access'?env.jwtExpiresIn:env.jwtRefreshExpiresIn) as SignOptions['expiresIn']});
export async function register(req:Request,res:Response){const {email,password,name,shopDomain,birthday}=req.body;const normalizedShop=String(shopDomain).toLowerCase();const normalizedEmail=String(email).toLowerCase();const shop=await Shop.findOne({shopDomain:normalizedShop,isActive:true}).select('+accessToken');if(!shop)throw new AppError('Shop not found',404,'SHOP_NOT_FOUND');let customer=await Customer.findOne({shopDomain:normalizedShop,email:normalizedEmail}).select('+portalPasswordHash');if(customer?.portalPasswordHash)throw new AppError('An account already exists for this email',409,'ACCOUNT_EXISTS');let shopifyCustomer=null;try{shopifyCustomer=await findShopifyCustomerByEmail(shop,normalizedEmail);}catch{/* Portal registration remains available during Shopify API outages. */}const passwordHash=await bcrypt.hash(password,12);if(customer){customer.portalPasswordHash=passwordHash;customer.name=name||customer.name||shopifyCustomer?.displayName;if(birthday)customer.birthday=new Date(birthday);if(!customer.shopifyCustomerId&&shopifyCustomer?.id)customer.shopifyCustomerId=shopifyCustomer.id;await customer.save();}else customer=await Customer.create({shopDomain:normalizedShop,email:normalizedEmail,name:name||shopifyCustomer?.displayName,shopifyCustomerId:shopifyCustomer?.id,portalPasswordHash:passwordHash,birthday:birthday?new Date(birthday):undefined,referralCode:crypto.randomBytes(6).toString('hex').toUpperCase()});const hasSignupPoints=await Transaction.exists({shopDomain:normalizedShop,customerId:customer._id,source:'signup',type:'earn'});const signup=!hasSignupPoints?await LoyaltyRule.findOne({shopDomain:normalizedShop,type:'signup',isActive:true}):null;if(signup?.flatPoints)await awardPoints({shopDomain:normalizedShop,customerId:customer._id,points:signup.flatPoints,source:'signup',referenceId:`portal:${customer._id}`});return ok(res,{customerId:customer._id,email:customer.email,accessToken:sign(customer,'access'),refreshToken:sign(customer,'refresh')},201);}
export async function login(req:Request,res:Response){const customer=await Customer.findOne({shopDomain:String(req.body.shopDomain).toLowerCase(),email:String(req.body.email).toLowerCase(),isActive:true}).select('+portalPasswordHash');if(!customer?.portalPasswordHash||!await bcrypt.compare(req.body.password,customer.portalPasswordHash))throw new AppError('Invalid email or password',401,'INVALID_CREDENTIALS');return ok(res,{accessToken:sign(customer,'access'),refreshToken:sign(customer,'refresh')});}
export async function refresh(req:Request,res:Response){let payload:any;try{payload=jwt.verify(req.body.refreshToken,env.jwtSecret);}catch{throw new AppError('Invalid or expired refresh token',401,'INVALID_TOKEN');}if(payload.tokenType!=='refresh')throw new AppError('Refresh token required',401,'INVALID_TOKEN');const customer=await Customer.findOne({_id:payload.customerId,shopDomain:payload.shopDomain,isActive:true});if(!customer)throw new AppError('Customer not found',401,'UNAUTHORIZED');return ok(res,{accessToken:sign(customer,'access')});}
