import crypto from 'crypto';
import { Request, Response } from 'express';
import { ActivityLog } from '../models/ActivityLog';
import { Customer } from '../models/Customer';
import { LoyaltyRule } from '../models/LoyaltyRule';
import { Shop } from '../models/Shop';
import { Transaction } from '../models/Transaction';
import { logger } from '../config/logger';
import { awardPoints, calculatePurchasePoints, reverseOrderPoints } from '../services/pointsService';
import { claimWebhook, completeWebhook, failWebhook } from '../services/webhookIdempotencyService';
import { AppError } from '../utils/AppError';
type HandlerResult=Record<string,unknown>|void;
type Handler=(req:Request,shopDomain:string)=>Promise<HandlerResult>;
const wrapped=(action:string,handler:Handler)=>async(req:Request,res:Response)=>{const webhookId=req.header('X-Shopify-Webhook-Id');const shopDomain=(req.header('X-Shopify-Shop-Domain')||'').toLowerCase();const topic=req.header('X-Shopify-Topic')||action;if(!webhookId||!shopDomain)throw new AppError('Missing Shopify webhook headers',400,'MISSING_HEADERS');if(!await claimWebhook(shopDomain,webhookId,topic))return res.status(200).json({success:true,data:{duplicate:true}});logger.info('webhook_received',{webhookId,shopDomain,topic});try{const result=await handler(req,shopDomain);await completeWebhook(webhookId);const outcome=result||{outcome:'processed'};await ActivityLog.create({shopDomain,type:'webhook',action,metadata:{webhookId,topic,status:'processed',...outcome}});logger.info('webhook_processed',{webhookId,shopDomain,topic,...outcome});return res.status(200).json({success:true,data:{processed:true,...outcome}});}catch(error:any){await Promise.all([failWebhook(webhookId,error.message),ActivityLog.create({shopDomain,type:'error',action:`${action}_failed`,metadata:{webhookId,topic,message:error.message}})]);logger.error('webhook_failed',{webhookId,shopDomain,topic,message:error.message,stack:error.stack});throw error;}};
async function locateCustomer(shopDomain:string,payload:any){const shopifyCustomerId=String(payload.customer?.id||payload.customer_id||'');const email=payload.customer?.email||payload.email;let customer=shopifyCustomerId?await Customer.findOne({shopDomain,shopifyCustomerId}):null;if(!customer&&email)customer=await Customer.findOne({shopDomain,email:String(email).toLowerCase()});return customer;}
async function processPaidOrder(order:any,shopDomain:string):Promise<HandlerResult>{const orderId=String(order.id);if(await Transaction.exists({shopDomain,source:'order',referenceId:orderId,type:'earn'}))return{outcome:'already_recorded',orderId};let customer=await locateCustomer(shopDomain,order);if(!customer&&order.email)customer=await Customer.create({shopDomain,email:String(order.email).toLowerCase(),name:order.customer?.first_name,shopifyCustomerId:order.customer?.id?String(order.customer.id):undefined,referralCode:crypto.randomBytes(6).toString('hex').toUpperCase()});if(!customer)return{outcome:'skipped',reason:'customer_not_identified',orderId};const rules=await LoyaltyRule.find({shopDomain,type:'purchase',isActive:true});const total=Number(order.current_total_price??order.total_price??0);const points=rules.reduce((sum,r)=>sum+calculatePurchasePoints(total,r.pointsPerAmount||0,r.minSpend||0),0);await awardPoints({shopDomain,customerId:customer._id,points,source:'order',referenceId:orderId,totalSpend:total,orderAmount:total});return{outcome:'recorded',orderId,total,points};}
export const orderCreated=wrapped('orders/create',async()=>({outcome:'observed'}));
export const orderPaid=wrapped('orders/paid',async(req,shopDomain)=>processPaidOrder(req.body,shopDomain));
export const orderUpdated=wrapped('orders/updated',async(req,shopDomain)=>{const financialStatus=String(req.body.financial_status||'').toLowerCase();if(financialStatus!=='paid'&&financialStatus!=='partially_refunded')return{outcome:'ignored',reason:'order_not_paid',orderId:String(req.body.id)};return processPaidOrder(req.body,shopDomain);});
export const orderCancelled=wrapped('orders/cancelled',async(req,shopDomain)=>{const customer=await locateCustomer(shopDomain,req.body);if(customer)await reverseOrderPoints(shopDomain,customer._id,String(req.body.id));});
export const orderRefunded=wrapped('orders/refunded',async(req,shopDomain)=>{const payload=req.body,orderId=String(payload.order_id||payload.order?.id);const earned=await Transaction.findOne({shopDomain,source:'order',referenceId:orderId,type:'earn'});if(!earned)return;const customer=await Customer.findById(earned.customerId);if(!customer)return;const refunded=(payload.refund_line_items||[]).reduce((n:number,x:any)=>n+Number(x.subtotal||0),(payload.transactions||[]).reduce((n:number,x:any)=>n+Number(x.amount||0),0));const originalSpend=Math.max(Number(earned.orderAmount||payload.order?.total_price||0),refunded);const points=Math.floor(earned.points*Math.min(1,refunded/originalSpend));await reverseOrderPoints(shopDomain,customer._id,orderId,points);customer.totalSpend=Math.max(0,customer.totalSpend-refunded);await customer.save();});
export const customerCreated=wrapped('customers/create',async(req,shopDomain)=>{const p=req.body;let customer=await Customer.findOne({shopDomain,$or:[{shopifyCustomerId:String(p.id)},{email:String(p.email).toLowerCase()}]});if(!customer)customer=await Customer.create({shopDomain,shopifyCustomerId:String(p.id),email:String(p.email).toLowerCase(),name:[p.first_name,p.last_name].filter(Boolean).join(' '),referralCode:crypto.randomBytes(6).toString('hex').toUpperCase()});else{customer.shopifyCustomerId=String(p.id);customer.name=customer.name||[p.first_name,p.last_name].filter(Boolean).join(' ');await customer.save();}const rule=await LoyaltyRule.findOne({shopDomain,type:'signup',isActive:true});if(rule?.flatPoints)await awardPoints({shopDomain,customerId:customer._id,points:rule.flatPoints,source:'signup',referenceId:String(p.id)});});
export const appUninstalled=wrapped('app/uninstalled',async(_req,shopDomain)=>{await Shop.updateOne({shopDomain},{$set:{isActive:false,uninstalledAt:new Date()}});});
